#!c:\users\burksa\docume~1\python~1\venndor\venndo~1\flask\scripts\python.exe

print("""
The 'bokeh-server' command from versions 0.10 and earlier no longer exists.
Please see the documentation for the new 'bokeh' command here:

  http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html
""")
